name: libread_ryan
version: 1.0.0+1
publish_to: none
description: Project akhir UKK RPL 2024
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flexi_image_slider: ^1.0.8
  pretty_dio_logger: ^1.3.1
  auto_size_text: ^3.0.0
  email_validator: ^2.1.16
  persistent_bottom_nav_bar: ^5.0.2
  top_snackbar_flutter: ^3.1.0
  carousel_slider: ^4.2.1
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  lottie: ^2.0.0
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/image/
    - lib/assets/buku/

